name: Add new link
description:
labels: ["🆕 new link"]
body:

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary checks
      options:
        - label: "I have [read the Code of Conduct](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/code-of-conduct.md)"
        - label: "I applied all rules from the [Contributing guide](https://github.com/kdeldycke/awesome-falsehood/blob/main/.github/contributing.md)"
        - label: "I have checked there is no other [Issues](https://github.com/kdeldycke/awesome-falsehood/issues) or [Pull Requests](https://github.com/kdeldycke/awesome-falsehood/pulls) covering the same topic to open"
    validations:
      required: true

  - type: checkboxes
    id: affiliation
    attributes:
      label: Affiliation
      description: >
        Please indicate how you are associated with the new proposed content.
      options:
        - label: "I am the author of the article or project"
        - label: "I am working for/with the company which is publishing the article or project"
        - label: "I'm just a rando who stumbled upon this via social networks"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: >
        Explain the motivation for adding this link. What's special about it to add it to the current collection?
      placeholder: |
        This link is special because...
    validations:
      required: true