name: Lint Awesome List
on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/awesome-lint@v1

  validate_links:
    name: Validate links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install awesome_bot
        run : |
          gem install awesome_bot
      - name: Run awesome_bot
        run : |
          awesome_bot --files ./README.md --allow-ssl --allow-redirect --white-list creativecommons.org
