name: Lint Awesome List
on:
  push:
  pull_request:
  schedule:
    # Run linter every week to catch regressions from external dependencies.
    - cron: 17 9 * * 1

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Fetch the last 31 days to please linter's age checks.
      - run: |
          git checkout 'master@{31 days ago}'
      - uses: max/awesome-lint@master
